//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFixitTaskEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixItTask
    {
        public int FixItTaskId { get; set; }
        public string CreatedBy { get; set; }
        public string Owner { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public string PhotoUrl { get; set; }
        public bool IsDone { get; set; }
    }
}
